"""initial_schema

Revision ID: 7a1f5f11d72a
Revises: 
Create Date: 2025-12-09 18:46:39.297556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1f5f11d72a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ============================================================================
    # ROOT ENTITY: Tenant (organização/cliente)
    # ============================================================================
    op.create_table(
        'tenant',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('settings', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
    )
    op.create_index('ix_tenant_id', 'tenant', ['id'])
    op.create_index('ix_tenant_name', 'tenant', ['name'])
    op.create_index('ix_tenant_is_active', 'tenant', ['is_active'])
    
    # ============================================================================
    # USER: Usuários vinculados a tenant
    # ============================================================================
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'])
    op.create_index('ix_user_tenant_id', 'user', ['tenant_id'])
    op.create_index('ix_user_email', 'user', ['email'])
    op.create_index('ix_user_is_active', 'user', ['is_active'])
    op.create_index('ix_user_deleted_at', 'user', ['deleted_at'])
    op.create_index('idx_user_tenant_email', 'user', ['tenant_id', 'email'], unique=True)
    op.create_index('idx_user_tenant_active', 'user', ['tenant_id', 'is_active'])
    op.create_index('idx_user_deleted', 'user', ['deleted_at'])
    
    # ============================================================================
    # CORE: Agentes (Workers/Robôs)
    # ============================================================================
    op.create_table(
        'agente',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('machine_name', sa.String(), nullable=False),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('status', sa.String(20), nullable=True),
        sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
        sa.Column('capabilities', sa.JSON(), nullable=True),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agente_id', 'agente', ['id'])
    op.create_index('ix_agente_tenant_id', 'agente', ['tenant_id'])
    op.create_index('ix_agente_name', 'agente', ['name'])
    op.create_index('ix_agente_status', 'agente', ['status'])
    op.create_index('ix_agente_last_heartbeat', 'agente', ['last_heartbeat'])
    op.create_index('idx_agente_tenant_name', 'agente', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_agente_tenant_status', 'agente', ['tenant_id', 'status'])
    op.create_index('idx_agente_tenant_heartbeat', 'agente', ['tenant_id', 'last_heartbeat'])
    
    # ============================================================================
    # CORE: Processos (Automações RPA)
    # ============================================================================
    op.create_table(
        'processo',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('tipo', sa.String(20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processo_id', 'processo', ['id'])
    op.create_index('ix_processo_tenant_id', 'processo', ['tenant_id'])
    op.create_index('ix_processo_name', 'processo', ['name'])
    op.create_index('ix_processo_is_active', 'processo', ['is_active'])
    op.create_index('idx_processo_tenant_name', 'processo', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_processo_tenant_active', 'processo', ['tenant_id', 'is_active'])
    
    # ============================================================================
    # CORE: Versões de Processo
    # ============================================================================
    op.create_table(
        'versao_processo',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('processo_id', sa.Uuid(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('package_path', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('release_notes', sa.String(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['processo_id'], ['processo.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_versao_processo_id', 'versao_processo', ['id'])
    op.create_index('ix_versao_processo_tenant_id', 'versao_processo', ['tenant_id'])
    op.create_index('ix_versao_processo_processo_id', 'versao_processo', ['processo_id'])
    op.create_index('ix_versao_processo_is_active', 'versao_processo', ['is_active'])
    op.create_index('idx_versao_tenant_processo_version', 'versao_processo', 
                    ['tenant_id', 'processo_id', 'version'], unique=True)
    op.create_index('idx_versao_processo_active', 'versao_processo', 
                    ['processo_id', 'is_active'])
    
    # ============================================================================
    # CORE: Execuções de Processo
    # ============================================================================
    op.create_table(
        'execucao',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('processo_id', sa.Uuid(), nullable=False),
        sa.Column('versao_processo_id', sa.Uuid(), nullable=False),
        sa.Column('agente_id', sa.Uuid(), nullable=False),
        sa.Column('status', sa.String(20), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('trigger_type', sa.String(20), nullable=False),
        sa.Column('correlation_id', sa.String(), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['agente_id'], ['agente.id']),
        sa.ForeignKeyConstraint(['processo_id'], ['processo.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.ForeignKeyConstraint(['versao_processo_id'], ['versao_processo.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execucao_id', 'execucao', ['id'])
    op.create_index('ix_execucao_tenant_id', 'execucao', ['tenant_id'])
    op.create_index('ix_execucao_processo_id', 'execucao', ['processo_id'])
    op.create_index('ix_execucao_versao_processo_id', 'execucao', ['versao_processo_id'])
    op.create_index('ix_execucao_agente_id', 'execucao', ['agente_id'])
    op.create_index('ix_execucao_status', 'execucao', ['status'])
    op.create_index('ix_execucao_correlation_id', 'execucao', ['correlation_id'])
    op.create_index('idx_execucao_tenant_status_created', 'execucao', 
                    ['tenant_id', 'status', 'created_at'])
    op.create_index('idx_execucao_tenant_processo_created', 'execucao', 
                    ['tenant_id', 'processo_id', 'created_at'])
    op.create_index('idx_execucao_correlation', 'execucao', ['correlation_id'])
    
    # ============================================================================
    # WORKLOAD: Fila de Itens de Trabalho
    # ============================================================================
    op.create_table(
        'item_fila',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('processo_id', sa.Uuid(), nullable=False),
        sa.Column('queue_name', sa.String(), nullable=False),
        sa.Column('priority', sa.String(20), nullable=True),
        sa.Column('status', sa.String(20), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('processed_by_agente_id', sa.Uuid(), nullable=True),
        sa.Column('execution_id', sa.Uuid(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['execution_id'], ['execucao.id']),
        sa.ForeignKeyConstraint(['processed_by_agente_id'], ['agente.id']),
        sa.ForeignKeyConstraint(['processo_id'], ['processo.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_fila_id', 'item_fila', ['id'])
    op.create_index('ix_item_fila_tenant_id', 'item_fila', ['tenant_id'])
    op.create_index('ix_item_fila_processo_id', 'item_fila', ['processo_id'])
    op.create_index('ix_item_fila_queue_name', 'item_fila', ['queue_name'])
    op.create_index('ix_item_fila_priority', 'item_fila', ['priority'])
    op.create_index('ix_item_fila_status', 'item_fila', ['status'])
    op.create_index('ix_item_fila_processed_by_agente_id', 'item_fila', ['processed_by_agente_id'])
    op.create_index('ix_item_fila_execution_id', 'item_fila', ['execution_id'])
    op.create_index('idx_itemfila_tenant_status_priority_created', 'item_fila',
                    ['tenant_id', 'status', 'priority', 'created_at'])
    op.create_index('idx_itemfila_tenant_queue_status', 'item_fila',
                    ['tenant_id', 'queue_name', 'status'])
    
    # ============================================================================
    # WORKLOAD: Exceções de Execução
    # ============================================================================
    op.create_table(
        'excecao',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('execucao_id', sa.Uuid(), nullable=False),
        sa.Column('tipo', sa.String(20), nullable=False),
        sa.Column('severity', sa.String(20), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('stack_trace', sa.String(), nullable=True),
        sa.Column('screenshot_path', sa.String(), nullable=True),
        sa.Column('context', sa.JSON(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['execucao_id'], ['execucao.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_excecao_id', 'excecao', ['id'])
    op.create_index('ix_excecao_tenant_id', 'excecao', ['tenant_id'])
    op.create_index('ix_excecao_execucao_id', 'excecao', ['execucao_id'])
    op.create_index('ix_excecao_severity', 'excecao', ['severity'])
    op.create_index('ix_excecao_is_resolved', 'excecao', ['is_resolved'])
    op.create_index('idx_excecao_tenant_execucao', 'excecao', ['tenant_id', 'execucao_id'])
    op.create_index('idx_excecao_tenant_severity_resolved', 'excecao',
                    ['tenant_id', 'severity', 'is_resolved'])
    
    # ============================================================================
    # GOVERNANCE: Assets (Variáveis/Configurações)
    # ============================================================================
    op.create_table(
        'asset',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('tipo', sa.String(20), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('scope', sa.String(20), nullable=False),
        sa.Column('scope_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['scope_id'], ['processo.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_id', 'asset', ['id'])
    op.create_index('ix_asset_tenant_id', 'asset', ['tenant_id'])
    op.create_index('ix_asset_name', 'asset', ['name'])
    op.create_index('ix_asset_scope', 'asset', ['scope'])
    op.create_index('ix_asset_scope_id', 'asset', ['scope_id'])
    op.create_index('idx_asset_tenant_name', 'asset', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_asset_tenant_scope', 'asset', ['tenant_id', 'scope'])
    
    # ============================================================================
    # GOVERNANCE: Credenciais (Criptografadas)
    # ============================================================================
    op.create_table(
        'credencial',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('tipo', sa.String(20), nullable=False),
        sa.Column('username', sa.String(255), nullable=True),
        sa.Column('encrypted_password', sa.String(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_rotated', sa.DateTime(), nullable=True),
        sa.Column('rotation_days', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credencial_id', 'credencial', ['id'])
    op.create_index('ix_credencial_tenant_id', 'credencial', ['tenant_id'])
    op.create_index('ix_credencial_name', 'credencial', ['name'])
    op.create_index('ix_credencial_expires_at', 'credencial', ['expires_at'])
    op.create_index('idx_credencial_tenant_name', 'credencial', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_credencial_expires', 'credencial', ['expires_at'])
    
    # ============================================================================
    # GOVERNANCE: Agendamentos (Cron)
    # ============================================================================
    op.create_table(
        'agendamento',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('processo_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('cron_expression', sa.String(), nullable=False),
        sa.Column('timezone', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['processo_id'], ['processo.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agendamento_id', 'agendamento', ['id'])
    op.create_index('ix_agendamento_tenant_id', 'agendamento', ['tenant_id'])
    op.create_index('ix_agendamento_processo_id', 'agendamento', ['processo_id'])
    op.create_index('ix_agendamento_is_active', 'agendamento', ['is_active'])
    op.create_index('ix_agendamento_next_run_at', 'agendamento', ['next_run_at'])
    op.create_index('idx_agendamento_tenant_active_next', 'agendamento',
                    ['tenant_id', 'is_active', 'next_run_at'])
    op.create_index('idx_agendamento_processo', 'agendamento', ['processo_id'])
    
    # ============================================================================
    # MONITORING: Auditoria de Eventos
    # ============================================================================
    op.create_table(
        'auditoria_evento',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('action', sa.String(20), nullable=False),
        sa.Column('old_values', sa.JSON(), nullable=True),
        sa.Column('new_values', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_evento_id', 'auditoria_evento', ['id'])
    op.create_index('ix_auditoria_evento_tenant_id', 'auditoria_evento', ['tenant_id'])
    op.create_index('ix_auditoria_evento_user_id', 'auditoria_evento', ['user_id'])
    op.create_index('ix_auditoria_evento_entity_type', 'auditoria_evento', ['entity_type'])
    op.create_index('ix_auditoria_evento_entity_id', 'auditoria_evento', ['entity_id'])
    op.create_index('ix_auditoria_evento_action', 'auditoria_evento', ['action'])
    op.create_index('idx_auditoria_tenant_entity', 'auditoria_evento',
                    ['tenant_id', 'entity_type', 'entity_id'])
    op.create_index('idx_auditoria_tenant_action_created', 'auditoria_evento',
                    ['tenant_id', 'action', 'created_at'])
    op.create_index('idx_auditoria_user', 'auditoria_evento', ['user_id'])
    
    # ============================================================================
    # MONITORING: Logs de Execução
    # ============================================================================
    op.create_table(
        'log_execucao',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('execucao_id', sa.Uuid(), nullable=False),
        sa.Column('level', sa.String(20), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('correlation_id', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('extra', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['execucao_id'], ['execucao.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_execucao_id', 'log_execucao', ['id'])
    op.create_index('ix_log_execucao_tenant_id', 'log_execucao', ['tenant_id'])
    op.create_index('ix_log_execucao_execucao_id', 'log_execucao', ['execucao_id'])
    op.create_index('ix_log_execucao_level', 'log_execucao', ['level'])
    op.create_index('ix_log_execucao_correlation_id', 'log_execucao', ['correlation_id'])
    op.create_index('idx_log_tenant_execucao_created', 'log_execucao',
                    ['tenant_id', 'execucao_id', 'created_at'])
    op.create_index('idx_log_correlation', 'log_execucao', ['correlation_id'])
    op.create_index('idx_log_level', 'log_execucao', ['level'])
    
    # ============================================================================
    # MONITORING: Metadados de Logs
    # ============================================================================
    op.create_table(
        'log_metadata',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('log_execucao_id', sa.Uuid(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('tipo', sa.String(20), nullable=False),
        sa.ForeignKeyConstraint(['log_execucao_id'], ['log_execucao.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_metadata_id', 'log_metadata', ['id'])
    op.create_index('ix_log_metadata_tenant_id', 'log_metadata', ['tenant_id'])
    op.create_index('ix_log_metadata_log_execucao_id', 'log_metadata', ['log_execucao_id'])
    op.create_index('ix_log_metadata_key', 'log_metadata', ['key'])
    op.create_index('idx_logmetadata_log_key', 'log_metadata', ['log_execucao_id', 'key'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Dropping in reverse order of creation (respecting foreign keys)
    op.drop_index('idx_logmetadata_log_key', 'log_metadata')
    op.drop_index('ix_log_metadata_key', 'log_metadata')
    op.drop_index('ix_log_metadata_log_execucao_id', 'log_metadata')
    op.drop_index('ix_log_metadata_tenant_id', 'log_metadata')
    op.drop_index('ix_log_metadata_id', 'log_metadata')
    op.drop_table('log_metadata')
    
    op.drop_index('idx_log_level', 'log_execucao')
    op.drop_index('idx_log_correlation', 'log_execucao')
    op.drop_index('idx_log_tenant_execucao_created', 'log_execucao')
    op.drop_index('ix_log_execucao_correlation_id', 'log_execucao')
    op.drop_index('ix_log_execucao_level', 'log_execucao')
    op.drop_index('ix_log_execucao_execucao_id', 'log_execucao')
    op.drop_index('ix_log_execucao_tenant_id', 'log_execucao')
    op.drop_index('ix_log_execucao_id', 'log_execucao')
    op.drop_table('log_execucao')
    
    op.drop_index('idx_auditoria_user', 'auditoria_evento')
    op.drop_index('idx_auditoria_tenant_action_created', 'auditoria_evento')
    op.drop_index('idx_auditoria_tenant_entity', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_action', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_entity_id', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_entity_type', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_user_id', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_tenant_id', 'auditoria_evento')
    op.drop_index('ix_auditoria_evento_id', 'auditoria_evento')
    op.drop_table('auditoria_evento')
    
    op.drop_index('idx_agendamento_processo', 'agendamento')
    op.drop_index('idx_agendamento_tenant_active_next', 'agendamento')
    op.drop_index('ix_agendamento_next_run_at', 'agendamento')
    op.drop_index('ix_agendamento_is_active', 'agendamento')
    op.drop_index('ix_agendamento_processo_id', 'agendamento')
    op.drop_index('ix_agendamento_tenant_id', 'agendamento')
    op.drop_index('ix_agendamento_id', 'agendamento')
    op.drop_table('agendamento')
    
    op.drop_index('idx_credencial_expires', 'credencial')
    op.drop_index('idx_credencial_tenant_name', 'credencial')
    op.drop_index('ix_credencial_expires_at', 'credencial')
    op.drop_index('ix_credencial_name', 'credencial')
    op.drop_index('ix_credencial_tenant_id', 'credencial')
    op.drop_index('ix_credencial_id', 'credencial')
    op.drop_table('credencial')
    
    op.drop_index('idx_asset_tenant_scope', 'asset')
    op.drop_index('idx_asset_tenant_name', 'asset')
    op.drop_index('ix_asset_scope_id', 'asset')
    op.drop_index('ix_asset_scope', 'asset')
    op.drop_index('ix_asset_name', 'asset')
    op.drop_index('ix_asset_tenant_id', 'asset')
    op.drop_index('ix_asset_id', 'asset')
    op.drop_table('asset')
    
    op.drop_index('idx_excecao_tenant_severity_resolved', 'excecao')
    op.drop_index('idx_excecao_tenant_execucao', 'excecao')
    op.drop_index('ix_excecao_is_resolved', 'excecao')
    op.drop_index('ix_excecao_severity', 'excecao')
    op.drop_index('ix_excecao_execucao_id', 'excecao')
    op.drop_index('ix_excecao_tenant_id', 'excecao')
    op.drop_index('ix_excecao_id', 'excecao')
    op.drop_table('excecao')
    
    op.drop_index('idx_itemfila_tenant_queue_status', 'item_fila')
    op.drop_index('idx_itemfila_tenant_status_priority_created', 'item_fila')
    op.drop_index('ix_item_fila_execution_id', 'item_fila')
    op.drop_index('ix_item_fila_processed_by_agente_id', 'item_fila')
    op.drop_index('ix_item_fila_status', 'item_fila')
    op.drop_index('ix_item_fila_priority', 'item_fila')
    op.drop_index('ix_item_fila_queue_name', 'item_fila')
    op.drop_index('ix_item_fila_processo_id', 'item_fila')
    op.drop_index('ix_item_fila_tenant_id', 'item_fila')
    op.drop_index('ix_item_fila_id', 'item_fila')
    op.drop_table('item_fila')
    
    op.drop_index('idx_execucao_correlation', 'execucao')
    op.drop_index('idx_execucao_tenant_processo_created', 'execucao')
    op.drop_index('idx_execucao_tenant_status_created', 'execucao')
    op.drop_index('ix_execucao_correlation_id', 'execucao')
    op.drop_index('ix_execucao_status', 'execucao')
    op.drop_index('ix_execucao_agente_id', 'execucao')
    op.drop_index('ix_execucao_versao_processo_id', 'execucao')
    op.drop_index('ix_execucao_processo_id', 'execucao')
    op.drop_index('ix_execucao_tenant_id', 'execucao')
    op.drop_index('ix_execucao_id', 'execucao')
    op.drop_table('execucao')
    
    op.drop_index('idx_versao_processo_active', 'versao_processo')
    op.drop_index('idx_versao_tenant_processo_version', 'versao_processo')
    op.drop_index('ix_versao_processo_is_active', 'versao_processo')
    op.drop_index('ix_versao_processo_processo_id', 'versao_processo')
    op.drop_index('ix_versao_processo_tenant_id', 'versao_processo')
    op.drop_index('ix_versao_processo_id', 'versao_processo')
    op.drop_table('versao_processo')
    
    op.drop_index('idx_processo_tenant_active', 'processo')
    op.drop_index('idx_processo_tenant_name', 'processo')
    op.drop_index('ix_processo_is_active', 'processo')
    op.drop_index('ix_processo_name', 'processo')
    op.drop_index('ix_processo_tenant_id', 'processo')
    op.drop_index('ix_processo_id', 'processo')
    op.drop_table('processo')
    
    op.drop_index('idx_agente_tenant_heartbeat', 'agente')
    op.drop_index('idx_agente_tenant_status', 'agente')
    op.drop_index('idx_agente_tenant_name', 'agente')
    op.drop_index('ix_agente_last_heartbeat', 'agente')
    op.drop_index('ix_agente_status', 'agente')
    op.drop_index('ix_agente_name', 'agente')
    op.drop_index('ix_agente_tenant_id', 'agente')
    op.drop_index('ix_agente_id', 'agente')
    op.drop_table('agente')
    
    op.drop_index('idx_user_deleted', 'user')
    op.drop_index('idx_user_tenant_active', 'user')
    op.drop_index('idx_user_tenant_email', 'user')
    op.drop_index('ix_user_deleted_at', 'user')
    op.drop_index('ix_user_is_active', 'user')
    op.drop_index('ix_user_email', 'user')
    op.drop_index('ix_user_tenant_id', 'user')
    op.drop_index('ix_user_id', 'user')
    op.drop_table('user')
    
    op.drop_index('ix_tenant_is_active', 'tenant')
    op.drop_index('ix_tenant_name', 'tenant')
    op.drop_index('ix_tenant_id', 'tenant')
    op.drop_table('tenant')
    
    # ### end Alembic commands ###
