"""initial_schema_fixed

Revision ID: 27e4b12afa72
Revises: 
Create Date: 2025-12-30 10:39:01.189230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e4b12afa72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sa.Enum('text', 'integer', 'boolean', 'json', name='tipoassetenum'), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=False)
    op.create_index(op.f('ix_asset_tenant_id'), 'asset', ['tenant_id'], unique=False)
    op.create_table('credencial',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_rotated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credencial_name'), 'credencial', ['name'], unique=False)
    op.create_index(op.f('ix_credencial_tenant_id'), 'credencial', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('agente',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('machine_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', 'MAINTENANCE', name='statusagenteenum'), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agente_tenant_name', 'agente', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_agente_id'), 'agente', ['id'], unique=False)
    op.create_index(op.f('ix_agente_tenant_id'), 'agente', ['tenant_id'], unique=False)
    op.create_table('item_fila',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRY', name='statusitemfilaenum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_fila_id'), 'item_fila', ['id'], unique=False)
    op.create_index(op.f('ix_item_fila_priority'), 'item_fila', ['priority'], unique=False)
    op.create_index(op.f('ix_item_fila_queue_name'), 'item_fila', ['queue_name'], unique=False)
    op.create_index(op.f('ix_item_fila_reference'), 'item_fila', ['reference'], unique=False)
    op.create_index(op.f('ix_item_fila_status'), 'item_fila', ['status'], unique=False)
    op.create_index(op.f('ix_item_fila_tenant_id'), 'item_fila', ['tenant_id'], unique=False)
    op.create_table('processo',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('ATTENDED', 'UNATTENDED', 'HYBRID', name='tipoprocessoenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processo_tenant_name', 'processo', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_processo_id'), 'processo', ['id'], unique=False)
    op.create_index(op.f('ix_processo_tenant_id'), 'processo', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_tenant', 'user', ['email', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)
    op.create_table('auditoria_evento',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auditoria_tenant_action_created', 'auditoria_evento', ['tenant_id', 'action', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_auditoria_tenant_entity', 'auditoria_evento', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('idx_auditoria_user', 'auditoria_evento', ['user_id'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_action'), 'auditoria_evento', ['action'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_entity_id'), 'auditoria_evento', ['entity_id'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_entity_type'), 'auditoria_evento', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_id'), 'auditoria_evento', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_tenant_id'), 'auditoria_evento', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auditoria_evento_user_id'), 'auditoria_evento', ['user_id'], unique=False)
    op.create_table('excecao',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_fila_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('tipo', sa.Enum('BUSINESS', 'SYSTEM', name='tipoexcecaoenum'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stack_trace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('screenshot_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_fila_id'], ['item_fila.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excecao_id'), 'excecao', ['id'], unique=False)
    op.create_table('versao_processo',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processo_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('package_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versao_processo_id'), 'versao_processo', ['id'], unique=False)
    op.create_index(op.f('ix_versao_processo_processo_id'), 'versao_processo', ['processo_id'], unique=False)
    op.create_index(op.f('ix_versao_processo_tenant_id'), 'versao_processo', ['tenant_id'], unique=False)
    op.create_table('execucao',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processo_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('agente_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('versao_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='statusexecucaoenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['versao_processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execucao_id'), 'execucao', ['id'], unique=False)
    op.create_index(op.f('ix_execucao_processo_id'), 'execucao', ['processo_id'], unique=False)
    op.create_index(op.f('ix_execucao_tenant_id'), 'execucao', ['tenant_id'], unique=False)
    op.create_table('log_execucao',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execucao_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucao.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_correlation', 'log_execucao', ['correlation_id'], unique=False)
    op.create_index('idx_log_level', 'log_execucao', ['level'], unique=False)
    op.create_index('idx_log_tenant_execucao_created', 'log_execucao', ['tenant_id', 'execucao_id', sa.text('created_at ASC')], unique=False)
    op.create_index(op.f('ix_log_execucao_correlation_id'), 'log_execucao', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_log_execucao_execucao_id'), 'log_execucao', ['execucao_id'], unique=False)
    op.create_index(op.f('ix_log_execucao_id'), 'log_execucao', ['id'], unique=False)
    op.create_index(op.f('ix_log_execucao_level'), 'log_execucao', ['level'], unique=False)
    op.create_index(op.f('ix_log_execucao_tenant_id'), 'log_execucao', ['tenant_id'], unique=False)
    op.create_table('log_metadata',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_execucao_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['log_execucao_id'], ['log_execucao.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logmetadata_log_key', 'log_metadata', ['log_execucao_id', 'key'], unique=False)
    op.create_index(op.f('ix_log_metadata_id'), 'log_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_log_metadata_key'), 'log_metadata', ['key'], unique=False)
    op.create_index(op.f('ix_log_metadata_log_execucao_id'), 'log_metadata', ['log_execucao_id'], unique=False)
    op.create_index(op.f('ix_log_metadata_tenant_id'), 'log_metadata', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_metadata_tenant_id'), table_name='log_metadata')
    op.drop_index(op.f('ix_log_metadata_log_execucao_id'), table_name='log_metadata')
    op.drop_index(op.f('ix_log_metadata_key'), table_name='log_metadata')
    op.drop_index(op.f('ix_log_metadata_id'), table_name='log_metadata')
    op.drop_index('idx_logmetadata_log_key', table_name='log_metadata')
    op.drop_table('log_metadata')
    op.drop_index(op.f('ix_log_execucao_tenant_id'), table_name='log_execucao')
    op.drop_index(op.f('ix_log_execucao_level'), table_name='log_execucao')
    op.drop_index(op.f('ix_log_execucao_id'), table_name='log_execucao')
    op.drop_index(op.f('ix_log_execucao_execucao_id'), table_name='log_execucao')
    op.drop_index(op.f('ix_log_execucao_correlation_id'), table_name='log_execucao')
    op.drop_index('idx_log_tenant_execucao_created', table_name='log_execucao')
    op.drop_index('idx_log_level', table_name='log_execucao')
    op.drop_index('idx_log_correlation', table_name='log_execucao')
    op.drop_table('log_execucao')
    op.drop_index(op.f('ix_execucao_tenant_id'), table_name='execucao')
    op.drop_index(op.f('ix_execucao_processo_id'), table_name='execucao')
    op.drop_index(op.f('ix_execucao_id'), table_name='execucao')
    op.drop_table('execucao')
    op.drop_index(op.f('ix_versao_processo_tenant_id'), table_name='versao_processo')
    op.drop_index(op.f('ix_versao_processo_processo_id'), table_name='versao_processo')
    op.drop_index(op.f('ix_versao_processo_id'), table_name='versao_processo')
    op.drop_table('versao_processo')
    op.drop_index(op.f('ix_excecao_id'), table_name='excecao')
    op.drop_table('excecao')
    op.drop_index(op.f('ix_auditoria_evento_user_id'), table_name='auditoria_evento')
    op.drop_index(op.f('ix_auditoria_evento_tenant_id'), table_name='auditoria_evento')
    op.drop_index(op.f('ix_auditoria_evento_id'), table_name='auditoria_evento')
    op.drop_index(op.f('ix_auditoria_evento_entity_type'), table_name='auditoria_evento')
    op.drop_index(op.f('ix_auditoria_evento_entity_id'), table_name='auditoria_evento')
    op.drop_index(op.f('ix_auditoria_evento_action'), table_name='auditoria_evento')
    op.drop_index('idx_auditoria_user', table_name='auditoria_evento')
    op.drop_index('idx_auditoria_tenant_entity', table_name='auditoria_evento')
    op.drop_index('idx_auditoria_tenant_action_created', table_name='auditoria_evento')
    op.drop_table('auditoria_evento')
    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index('idx_user_email_tenant', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_processo_tenant_id'), table_name='processo')
    op.drop_index(op.f('ix_processo_id'), table_name='processo')
    op.drop_index('idx_processo_tenant_name', table_name='processo')
    op.drop_table('processo')
    op.drop_index(op.f('ix_item_fila_tenant_id'), table_name='item_fila')
    op.drop_index(op.f('ix_item_fila_status'), table_name='item_fila')
    op.drop_index(op.f('ix_item_fila_reference'), table_name='item_fila')
    op.drop_index(op.f('ix_item_fila_queue_name'), table_name='item_fila')
    op.drop_index(op.f('ix_item_fila_priority'), table_name='item_fila')
    op.drop_index(op.f('ix_item_fila_id'), table_name='item_fila')
    op.drop_table('item_fila')
    op.drop_index(op.f('ix_agente_tenant_id'), table_name='agente')
    op.drop_index(op.f('ix_agente_id'), table_name='agente')
    op.drop_index('idx_agente_tenant_name', table_name='agente')
    op.drop_table('agente')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_credencial_tenant_id'), table_name='credencial')
    op.drop_index(op.f('ix_credencial_name'), table_name='credencial')
    op.drop_table('credencial')
    op.drop_index(op.f('ix_asset_tenant_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
