"""add deferred_until column

Revision ID: 4b0770c0a363
Revises: 27e4b12afa72
Create Date: 2026-01-15 13:24:18.261369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b0770c0a363'
down_revision: Union[str, None] = '27e4b12afa72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Cria o tipo ENUM se ele nao existir
    op.execute("DO $$ BEGIN CREATE TYPE priorityenum AS ENUM ('LOW', 'NORMAL', 'HIGH', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Tenta criar a tabela agendamento (caso nao exista)
    # Se der erro de "relation already exists", o proprio alembic gerencia ou ignoramos aqui
    # Mas como o script original recriava, vamos manter a estrutura segura:
    
    # Check if table exists before creating (Safe approach)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'agendamento' not in tables:
        op.create_table('agendamento',
        sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('process_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column('last_run', sa.DateTime(), nullable=True),
        sa.Column('next_run', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['process_id'], ['processo.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agendamento_id'), 'agendamento', ['id'], unique=False)
        op.create_index(op.f('ix_agendamento_tenant_id'), 'agendamento', ['tenant_id'], unique=False)

    # Colunas novas nas tabelas existentes (isso eh o que esta faltando e causando erro 500)
    
    # Asset
    op.add_column('asset', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset', sa.Column('process_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    
    # ... Ajustes de tipo (DateTime com timezone) ...
    # Para simplificar no Windows e evitar erro de cast, vamos focar nas colunas novas vitais
    
    # Credencial
    op.add_column('credencial', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    
    # Excecao
    op.add_column('excecao', sa.Column('execucao_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # Remove screenshot antiga se existir
    # op.drop_column('excecao', 'screenshot_path') 
    
    # ITEM FILA (O CRITICO)
    op.add_column('item_fila', sa.Column('deferred_until', sa.DateTime(), nullable=True))
    op.add_column('item_fila', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('item_fila', sa.Column('processo_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('item_fila', sa.Column('execucao_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))

    # --- FIX CRITICO: Substituicao de Coluna Priority ---
    op.drop_column('item_fila', 'priority')
    op.add_column('item_fila', sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='priorityenum'), server_default='NORMAL', nullable=False))
    # ----------------------------------------------------

    # Processo e Versao
    op.add_column('processo', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('versao_processo', sa.Column('package_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('versao_processo', sa.Column('release_notes', sa.Text(), nullable=True))
    op.add_column('versao_processo', sa.Column('config', sa.JSON(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    pass